### ISSUE TITLE
可以支持动态markdown 吗

### ISSUE THREAD

**Issue by cococa** [unplugin/unplugin-vue-markdown#27]
### Clear and concise description of the problem

比如
// const AsyncMarkDown = defineAsyncComponent(
//   () => import("../../public/markdown/xxx.md")
// );

### Suggested solution

。。。。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This is a compile-time plugin, runtime support is out-of-scope.
