### ISSUE TITLE
Automatically convert internal links to router links.

### ISSUE THREAD

**Issue by f3ve** [unplugin/unplugin-vue-markdown#37]
### Clear and concise description of the problem

Currently to create an internal link you have to manually write a `RouterLink`. 

```md
This is my markdown

This is an internal <RouterLink to="/example">link</RouterLink>
```

I would like to write internal links like regular markdown links and have it automatically convert to a `RouterLink`

```md
This is my markdown

This is an internal [link](/example)
```

### Suggested solution

All links that are only a path: E.G. `/` or `/example/path` and don't start with a website url like `https://example.com/example/path` should be treated like internal links.

In unplugin-vue-markdown options add a `internalLinkComponent` option, similar to the `wrapperComponent` option: 

```js
Markdown({
  internalLinkComponent: 'RouterLink'
})
```

This would also allow users to pass a custom router link component

```js
Markdown({
  internalLinkComponent: 'MyCustomRouterLink`
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good, PR welcome!
