### ISSUE TITLE
Getting ES Module Error 

### ISSUE THREAD

**Issue by yatendra121** [unplugin/unplugin-vue-markdown#48]
### Describe the bug

I have added configuration of in vite.config.ts. after then, when i am trying to start development server it has throwing error that given below. 

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/yatendrakushwaha/my-workspace/qnx-vuetify-sample/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/common/html_blocks.mjs not supported.
Instead change the require of /Users/yatendrakushwaha/my-workspace/qnx-vuetify-sample/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/common/html_blocks.mjs to a dynamic import() which is available in all CommonJS modules.

### Reproduction

https://github.com/yatendra121/qnx-vuetify-sample/tree/markdown

### System Info

```Shell
Mac, Chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by meteorlxy** [comment]
A bug from mdit-vue

**Comment by meteorlxy** [comment]
@yatendra121 Should have been fixed by `@mdit/plugin-component@2.1.1`. You can try to upgrade your dependency.

**Comment by yatendra121** [comment]
@meteorlxy 

> @yatendra121 Should have been fixed by `@mdit-vue/plugin-component@2.1.1`. You can try to upgrade your dependency.

It is working now.
But i am facing an issue that codes have not highlighted. i have already tested with different config but the codes are looking as simple text.
